mapps/labels/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import func
import random

from mapps import app, db
from mapps.models import Label
from mapps.main.utils import getRandomColor, get_icon_list

labels = Blueprint('labels', __name__)

def get_random_icon():
    labels = Label.query.all()
    #get list of all icons
    icons = get_icon_list()
    used_icons = []
    for label in labels:
        used_icons.append(label.icon)
    #remove used icons
    unused_icons = [x for x in icons if x not in used_icons]
    rand_icon = random.choice(unused_icons)
    return rand_icon

@labels.route("/labels")
@login_required
def labels_library():
    icons = get_icon_list()
    folder_dir="/Icon_Library/sets/all/"
    labels = Label.query.all()
    filename_path = "images/icon_svgs/"
    return render_template('labels.html', icons=icons, labels=labels, filename_path=filename_path, folder_dir=folder_dir, get_random_icon=get_random_icon, today=today)

@labels.route('/add_label', methods=['POST'])
@login_required
def add_label():
    label_name = request.form.get("labelName")
    old_label = Label.query.filter(func.lower(Label.name)==label_name.lower()).first()

    icon = request.form.get("labelIcon")
    if icon == "" or icon == None:
        flash("Label must have an icon", "warning")
        return redirect(url_for('labels.labels_library'))
    if current_user.is_authenticated:
        author = current_user
    
    new_label = Label(author=author, name=label_name, color=color, icon=icon)
    db.session.add(new_label)
    db.session.commit()
    print("new label",new_label.icon)
    print("color",new_label.color)

    return redirect(url_for('labels.labels_library'))


@labels.route("/delete_label/<int:label_id>", methods=['POST'])
@login_required
def delete_label(label_id):
    label_item = Label.query.get_or_404(label_id)
    db.session.delete(label_item)
    db.session.commit()
    return redirect(url_for('labels.labels_library'))

mapps/notes/routes.py
from datetime import datetime
import re
from flask import Blueprint, render_template, redirect, url_for, request, flash, make_response, json, jsonify
from flask_login import current_user, login_required

from mapps import db

from mapps.models import Note, Label, User, Update
from mapps.main.utils import redirect_url

notes = Blueprint('notes', __name__)

def getNumbers(str):
    array = re.findall(r'[0-9]+', str)
    return array

@notes.route("/notes")
@login_required
def notes_app():
    if current_user.is_authenticated:
        labels = Label.query.filter_by(author=current_user).all()
        notes = Note.query.filter_by(author=current_user).all()
        folder_dir="/Icon_Library/sets/all/"
        return render_template("notes.html", notes=notes, labels=labels, folder_dir=folder_dir, today=today)
    else:
        flash("You must be looged in to view this page", "info")
        return redirect(redirect_url())

@notes.route("/add_note", methods=['POST'])
@login_required
def add_note():
    if current_user.is_authenticated:
        user = User.query.filter_by(email=current_user.email).first()
        title = request.form.get("noteTitle")
        content = request.form.get("noteContent")
        labels = request.form.get("labels-list")

        if content == None or content == "":
            return redirect(redirect_url())
        newNote = Note(author=user, title=title, content=content)
        db.session.add(newNote)
        new_update = Update(author=user, column = None, message = "created")
        db.session.add(new_update)
        newNote.updates.append(new_update)

        if labels:
            label_ids = getNumbers(labels)
            print("label_ids", label_ids)
            for label in label_ids:
                new_label = Label.query.get_or_404(label)
                newNote.labels.append(new_label)
        else:
            print("no labels")
       
        print("newNote", newNote)
        print("new_update", new_update)
        print("newNote.updates.", newNote.updates)
        print("note labels", labels)
        print("note labels", labels)
        db.session.commit()
        flash("Note has been created", "success")
        return redirect(redirect_url())




@notes.route("/update_labels/note/<int:note_id>", methods=['POST'])
def update_labels(note_id):
    if current_user.is_authenticated:
        note_item = Note.query.get_or_404(note_id)
        if request.get_json():
            req = request.get_json()
            res = make_response(jsonify(req), 200)
            print(req)
            print("res", res)
            for _,v in req.items():
                proj_label = Label.query.get_or_404(int(v))
                proj_label.notes.append(note_item)
                db.session.commit()
            return res

@notes.route("/remove_labels/note/<int:note_id>", methods=['POST'])
def remove_labels(note_id):
    if current_user.is_authenticated:
        note_item = Note.query.get_or_404(note_id)
        if request.get_json():
            req = request.get_json()
            res = make_response(jsonify(req), 200)
            print(req)
            print("res", res)
            for _,v in req.items():
                proj_label = Label.query.get_or_404(int(v))
                proj_label.notes.remove(note_item)
                db.session.commit()
            return res





@notes.route("/update_note/<int:note_id>", methods=['POST'])
@login_required
def update_note(note_id):
    note_item = Note.query.get_or_404(note_item)
    title = request.form.get("noteTitle")
    content = request.form.get("noteContent")
    labels = request.form.get("noteLabels")
    if content == None or content == "":
        if title == None or title == "":
            db.session.delete(note_item)
            db.session.commit()
            return redirect(redirect_url())
    if title != note_item.title:
        note_title_update = Update(column = "title", message = "changed")
        db.session.add(note_title_update)
        note_item.title = title
        note_item.updates.append(note_title_update)
    if content != note_item.content:
        note_content_update = Update(column = "content", message = "changed")
        db.session.add(note_content_update)
        note_item.content = content
        note_item.updates.append(note_content_update)
    db.session.commit()
    flash("Note has been updated", "success")
    return redirect(redirect_url())




@notes.route("/delete_note/<int:note_id>", methods=['POST'])
@login_required
def delete_note(note_id):
    if current_user.is_authenticated:
        note_item = Note.query.get_or_404(note_id)
        db.session.delete(note_item)
        db.session.commit()
        return redirect(redirect_url())

""" 

def delete_note()

def update_note()

def add_note_note()
 """

mapps/tasks/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, make_response, jsonify, flash
from flask_login import current_user
from mapps import db
from mapps.models import Task, User, Project, Update
from mapps.main.utils import convert_for_model, redirect_url


tasks = Blueprint('tasks', __name__)


@tasks.route('/add_task/<int:project_id>', methods=['POST'])
def add_task(project_id):
    if project_id == None:
        project = None
    else: 
        project = Project.query.get_or_404(project_id)
    title = request.form.get("add-title")
    if title == "" or title == None:
        flash("Task Title cannot be left blank", "warning")
    else:
        description=request.form.get("description")
        new_task = Task(author=current_user, title=title, description=description, complete=False, deleted=False, priority=0)
        new_update = Update(author=current_user)
        db.session.add(new_task)
        db.session.add(new_update)
        project.tasks.append(new_task)
        project.updates.append(new_update)
        db.session.commit()
        return redirect(redirect_url())



@tasks.route('/add_task_no_project', methods=['POST'])
def add_task_no_project():
    if request.get_json():
        req = request.get_json()
        title = req['title']
        if title == "" or title == None:
            return 
        else:
            description = req['description']
            due_date = req['due_date']
            priority = req['priority']
            if due_date == None or due_date=='':
                due_date = None
            else:
                if len(due_date) == 19:
                    due_date=convert_for_model(due_date)
                elif len(due_date) == 14:
                    due_date = due_date[0:10]
                    due_date=convert_for_model(due_date)
                elif len(due_date) < 10:
                    due_date = None
            if priority == None:
                pass
            else:
                priority = priority
            new_task = Task(author=current_user, title=title, description=description, complete=False, deleted=False, priority=priority, due_date=due_date)
            db.session.add(new_task)
            db.session.commit()
            req.update({"id":new_task.id})
            res = make_response(jsonify(req), 200)
            print("req", req)
            print("res",res)
            
            return res


    

@tasks.route("/delete_task/<int:task_id>", methods=['POST'])
def delete_task(task_id):
    if request.get_json():
        req = request.get_json()
        task_item = Task.query.get_or_404(task_id)
        db.session.delete(task_item)
        db.session.commit()
        res = make_response(jsonify(req), 200)
        return res

@tasks.route("/delete_proj_task/<int:task_id>", methods=['POST'])
def delete_task_from_proj(task_id):
    print("task_id", task_id)
    if request.method == 'POST':
        task_item = Task.query.get_or_404(task_id)
        db.session.delete(task_item)
        db.session.commit()
        return redirect(redirect_url())


@tasks.route("/complete_task/<int:task_id>", methods=['POST'])
def complete_task(task_id):
    task_item = Task.query.get_or_404(task_id)
    task_item.complete = True
    db.session.commit()
    return redirect(redirect_url())

@tasks.route("/undo_task/<int:task_id>")
def undo_task(task_id):
    task_item = Task.query.get_or_404(task_id)
    task_item.complete = False
    task_item.deleted = False
    db.session.commit()
    return redirect(redirect_url())




@tasks.route("/update_task/<int:task_id>", methods=['POST'])
def update_task(task_id):
    task_item = Task.query.get_or_404(task_id)
    title = request.form.get("editTaskTitle")
    description = request.form.get("editTaskDescription")
    due_date = request.form.get("editTaskDueDate")
    due_date_time = request.form.get("editTaskDueDateTime")
    priority = request.form.get("editTaskPriority")
    no_due_date = request.form.get("no_due_date")

    if title == "":
        pass
    else:
        task_item.title = title
    if description == "":
        pass
    else:
        task_item.description = description
    if priority == None:
        pass
    else:
        task_item.priority = priority
    if no_due_date == "on":
        task_item.due_date = None
    elif due_date == None or due_date=='':
        task_item.due_date = None
    else:
        due_date=convert_for_model(due_date)
        task_item.due_date = due_date
    db.session.commit()
    return redirect(redirect_url())

mapps/user/routes.py
from datetime import datetime
from email.message import EmailMessage
import smtplib

from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, current_user, logout_user, login_required

from mapps import db, bcrypt
from mapps.user.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, UpdateAccountForm

from mapps.models import User
from mapps.main.utils import redirect_url

user = Blueprint('user', __name__)


def ResetPW(email, token):
    EMAIL_ADDRESS = "zacharysturman@zsdynamics.com"
    EMAIL_PASSWORD = "gbahpqqbovaoavik"

    msg = EmailMessage()
    msg['Subject'] = 'Reset Password'
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = email
    link = url_for('user.reset_password', token=token, _external=True)
    msg.set_content(f"""To reset your password, visit the following link: {link}

If you did not make this request then simply ignore this email and no changes will take place
""")

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        smtp.send_message(msg)




@user.route("/register", methods=['GET', 'POST'])
def register():
    today = datetime.utcnow().date()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created. You may now log in', 'success')
        return redirect(url_for('user.login'))
    return render_template('register.html', title='Register', form=form, today=today)




@user.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user == None:
            flash("No user exists with that email. Please try again or create a new account.")
            return redirect(redirect_url())
        token = user.get_reset_token()
        email = form.email.data
        ResetPW(email, token)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('user.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@user.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    user = User.verify_reset_token(token)
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated. You may now log in', 'success')
        return redirect(url_for('user.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

 



@user.route("/login", methods=['GET', 'POST'])
def login():
    today = datetime.utcnow().date()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check your email and password', 'danger')
    return render_template('login.html', title='Login', form=form, today=today)

@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))









@user.route("/account", methods=['GET', 'POST'])
@login_required
def user_account():
    if current_user.is_authenticated:
        today = datetime.utcnow().date()
        form = UpdateAccountForm()
       
        if form.validate_on_submit():
            current_user.name = form.name.data
            current_user.email = form.email.data
            current_user.password = form.new_password.data
        elif request.method == 'GET':
            form.name.data = current_user.name
            form.email.data = current_user.email
        
        
        return render_template("user.html", today=today, form=form)
    return render_template('login.html', title='Login', today=today )

mapps/templates/icons.html
{% extends "layout.html" %}
{% block content %}

<h1 class="display-1 text-center">Icons</h1>

{% for icon in icons %}

<img class="m-1" src="{{ url_for('static', filename=folder_dir+icon) }}" width="40" height="40">

{% endfor %}



{% endblock content %}

mapps/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  {% if title %}
  <title>Mapps{{ title }}</title>
  {% else %}
  <title>Mapps</title>
  {% endif %}

  {% assets "scss_all" %}
  <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
  {% endassets %}

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

</head>

<body>




  <div id="fullPage">
    <div class="container-fluid bg-secondary" id="mainTopBar">
      <div class="me-2">
        <div class="row px-1 pb-2 ">
          {% if current_user.is_authenticated %}

          <nav class="navbar bg-secondary ps-0">
            <div class="container-fluid d-inline-flex">
              <a class="navbar-brand" href="{{ url_for('main.home') }}">
                <h3 class="text-light m-0 p-0"> <strong> {{ current_user.name|capitalize }}'s</strong> <span
                    class="fw-light">
                    Dashboard</span> </h3>
              </a>

              <div class="d-inline-flex ms-auto" id="navbarNav">
                <ul class="d-inline-flex gap-3">

                  <li class="nav-item">
                    <a class="nav-link text-light" href="{{ url_for('main.home') }}">Home</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
                      Account
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('user.user_account') }}">Settings</a></li>
                      <li><a class="dropdown-item" href="#">Help</a></li>
                      <li>
                        <hr class="dropdown-divider">
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                      </li>
                    </ul>
                  </li>

                </ul>
              </div>
            </div>
          </nav>

          


          {% else %}

          <nav class="navbar bg-secondary">
            <div class="container-fluid">
              <div class="navbar" id="navbarNav">
                <ul class="navbar-nav d-inline-flex flex-row">
                  <li class="nav-item me-2">
                    <a class="nav-link text-light" href="{{ url_for('user.login') }}">Login</a>
                  </li>
                  <li class="nav-item mx-2">
                    <a class="nav-link text-light" href="{{ url_for('user.register') }}">Register</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>



          {% endif %}

        </div>
      </div>

    </div>
    <div>
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }} opacity-75 mx-2 mt-1">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>

    {% block content %}

    {% endblock content %}
  </div>


  </div>











  <script src="https://kit.fontawesome.com/94b6904e8a.js" crossorigin="anonymous"></script>
  <script src="{{ url_for('static',filename='main.js') }}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
  </script>

  {% block script %}{% endblock %}


</body>

</html>





<!--     <div class="col-3 bg-light px-3 order-last lh-1">
      <ul>
        <li><strong>IP Address</strong> {{ request.remote_addr }}
        </li>
        <li><strong>Path</strong>{{ request.path }} </li>
        <li><strong>Query Params</strong>{{ request.args }} </li>
        <li><strong>HTTP Method</strong>{{ request.method }} </li>
      </ul>

      <div class="text-wrap text-break">
        <h2>Headers</h2>
        {% for header, value in request.headers %}
        <p><strong>{{ header }}</strong> {{ value }}</p>
        {% endfor %}
      </div>
    </div> -->

mapps/templates/tasks.html
{% extends "layout.html" %}
{% block content %}

<h1 class="display-1 text-center">Tasks</h1>

<form action="{{ url_for('tasks.add_task') }}" method="POST" class="mt-5">
    <div class="mb-3">
        <label for="new-task" class="form-label h5">New Task</label>
        <input id="add-title" name="add-title" type="text" class="form-control" placeholder="Task{{ tasks|length+1 }}"
            value="Task{{ tasks|length+1 }}">
        <button type="submit" class="btn btn-primary">+ Task</button>
        <input type="text" name="description">
    </div>
</form>

<p><em>active Tasks: {{ active_tasks|length }}</em></p>

{% if active_tasks|length == 0 %}
<h4 class="text-center mb-5"><em class="text-muted">
        ^^^to get started, add a new task^^^
    </em></h4>
{% endif %}

{% for task in active_tasks|sort(attribute='date_updated', reverse=True) %}

<div class="card my-2">
    {% if ((task.due_date) or (task.priority)) %}
    <div class="card-header text-muted">
        {% if task.priority %}
        {% if task.priority == 1 %}
        <strong>!</strong>
        {% endif %}
        {% if task.priority == 2 %}
        <strong>!!</strong>
        {% endif %}
        {% if task.priority == 3 %}
        <strong>!!!</strong>
        {% endif %}
        {% endif %}
        {% if task.due_date %}
        <b>due: </b>
        <b>{{ weekday_month_dd_yyy_local(task.due_date) }}</b>
        {% endif %}


    </div>
    {% endif %}


    <div class="card-body" id="card-body-perm{{ task.id }}">
        <div class="d-inline-flex justify-content-between w-100">
            <h5 class="card-title display-6"><i class="fa-solid fa-circle-check mx-2 text-muted"
                    onclick="markAsComplete('{{ task.id }}')"></i>{{ task.title }}
            </h5>
            <form id="markAsComplete{{ task.id }}" action="{{ url_for('tasks.complete_task', task_id=task.id) }}"
                methods="POST" role="form"></form>
            <div class="btn-group">
                <button id="edit-task-item{{ task.id }}" class="border-0 bg-transparent mx-1"><i
                        class="fa-solid fa-square-pen fa-2xl text-muted"
                        onclick="edittaskItem('{{ task.id }}')"></i></button>
                <button type="button" data-bs-toggle="modal" data-bs-target="#delete-task{{ task.id }}"
                    id="delete-task-item{{ task.id }}" class="border-0 bg-transparent mx-1"><i
                        class="fa-solid fa-trash fa-2xl text-muted"></i></button>
            </div>
        </div>
        {% if task.description %}
        <p class="card-text ms-5">{{ task.description }}</p>
        {% endif %}



    </div>

    <div class="card-body d-none" id="card-body-edit{{ task.id }}">
        <form action="{{ url_for('tasks.update_task', task_id=task.id) }}" method="POST" role="form">
            <div>
                <input name="new_title" class="card-title display-6 w-100" placeholder="{{ task.title }}">
                </input>

                <textarea placeholder="Enter a description.." name="description" class="form-control"
                    id="adddescription{{ task.id }}" rows="3"></textarea>

                <div class="my-2">
                    <label for="add-due-date{{ task.id }}">Add a due date</label>
                    <br>
                    <input class="form-control form-control-lg" id="add-due-date{{ task.id }}" type="date"
                        name="due_date">
                    <input name="no_due_date" type="checkbox" class="form-check-input" id="noDueDate">
                    <label class="form-check-label" for="noDueDate">No Due Date</label>
                </div>
                <br>

                <div>
                    <h6>Priority:</h6>
                    <div class="form-check">
                        <input value="0" class="form-check-input" type="radio" name="priority" id="priority-low">
                        <label class="form-check-label" for="priority-none">
                            None
                        </label>
                    </div>
                    <div class="form-check">


                        <input value="1" class="form-check-input" type="radio" name="priority" id="priority-low">
                        <label class="form-check-label" for="priority-low">
                            !
                        </label>

                    </div>
                    <div class="form-check">
                        <input value="2" class="form-check-input" type="radio" name="priority" id="priority-medium">
                        <label class="form-check-label" for="priority-medium">
                            !!
                        </label>

                    </div>
                    <div class="form-check">
                        <input value="3" class="form-check-input" type="radio" name="priority" id="priority-high">
                        <label class="form-check-label" for="priority-high">
                            !!!
                        </label>
                    </div>
                </div>
                <br>
                <div class="text-end">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <button type="reset" class="btn btn-secondary"
                            onclick="savetaskItem('{{ task.id }}')">Cancel</button>
                    </div>

                </div>
            </div>


        </form>

    </div>

    <div class="card-footer d-inline-flex justify-content-between">
        <div>
            <small><em>created: </em></small>
            <small>{{ wkd_mon_dd_yyy_local(task.date_added) }}</small>
            <small>{{ hh_mm_ss_am_local(task.date_added) }}</small>
        </div>
        <div>
            <small><em>updated: </em></small>
            <small>{{ wkd_mon_dd_yyy_local(task.date_updated) }}</small>
            <small>{{ hh_mm_ss_am_local(task.date_updated) }}</small>

        </div>
       


    </div>
</div>

<form action="{{ url_for('tasks.delete_task', task_id = task.id) }}" method="POST" role="form">
    <div class="modal fade" id="delete-task{{ task.id }}" tabindex="-1" aria-labelledby="delete-task{{ task.id }}Label"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete-task{{ task.id }}Label">Are you sure you want to delete
                        {{ task.title }} ?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </div>
    </div>
</form>











{% endfor %}



<div class="row">
    <div class="col">
        <div class="card text-center">
            <div class="card-header">
                Complete
            </div>
            <div class="card-body">

                {% for task in task_list %}
                {% if task.complete == True %}

                <p class="text-decoration-line-through text-success h5" onmouseover="showUndoBtns('{{ task.id }}')"
                    onmouseleave="hideUndoBtns('{{ task.id }}')">{{ task.title }}<i id="undo{{ task.id }}"
                        class="fa-solid fa-arrow-rotate-left d-none" onclick="puttaskItemBack('{{ task.id }}')"></i></p>

                <form id="undoForm{{ task.id }}" action="{{ url_for('undo_task', task_id=task.id) }}" methods="POST"
                    role="form"></form>

                {% endif %}
                {% endfor %}


            </div>
        </div>

    </div>
    <div class="col">
        <div class="card text-center">
            <div class="card-header">
                Deleted
            </div>
            <div class="card-body">

                <div>
                    {% for task in task_list %}
                    {% if task.deleted == True %}
                    <p class="text-decoration-line-through text-danger h5" onmouseover="showUndoBtns('{{ task.id }}')"
                        onmouseleave="hideUndoBtns('{{ task.id }}')">{{ task.title }}<i id="undo{{ task.id }}"
                            class="fa-solid fa-arrow-rotate-left d-none" onclick="puttaskItemBack('{{ task.id }}')"></i>
                    </p>
                    <form id="undoForm{{ task.id }}" action="{{ url_for('undo_task', task_id=task.id) }}" methods="POST"
                        role="form"></form>

                    {% endif %}
                    {% endfor %}

                </div>




            </div>
        </div>

    </div>
</div>





<script>
    function edittaskItem(task_id) {
        let permtaskBody = document.getElementById("card-body-perm" + task_id)
        let edittaskBody = document.getElementById("card-body-edit" + task_id)
        if (edittaskBody.classList.contains("d-none")) {
            edittaskBody.classList.remove("d-none")
        }
        if (!permtaskBody.classList.contains("d-none")) {
            permtaskBody.classList.add("d-none")
        }
    }

    function savetaskItem(task_id) {
        let permtaskBody = document.getElementById("card-body-perm" + task_id)
        let edittaskBody = document.getElementById("card-body-edit" + task_id)
        if (!edittaskBody.classList.contains("d-none")) {
            edittaskBody.classList.add("d-none")
        }
        if (permtaskBody.classList.contains("d-none")) {
            permtaskBody.classList.remove("d-none")
        }
    }

    function markAsComplete(task_id) {
        let form = document.getElementById("markAsComplete" + task_id)

        form.submit()

    }

    function showUndoBtns(task_id) {
        let undoBtn = document.getElementById('undo' + task_id)

        if (undoBtn.classList.contains('d-none')) {
            undoBtn.classList.remove('d-none')
        }
    }

    function hideUndoBtns(task_id) {
        let undoBtn = document.getElementById('undo' + task_id)

        if (!undoBtn.classList.contains('d-none')) {
            undoBtn.classList.add('d-none')
        }
    }

    function puttaskItemBack(task_id) {
        let form = document.getElementById("undoForm" + task_id)

        form.submit()
    }
</script>




{% endblock content %}